; Steam/EOS stay unlinked.
[/Script/Engine.CollisionProfile]
+DefaultChannelResponses=(Channel=ECC_GameTraceChannel1,Name="FfSim",DefaultResponse=ECR_Ignore,bTraceType=False,bStaticObject=False)
+DefaultChannelResponses=(Channel=ECC_GameTraceChannel2,Name="FfDress",DefaultResponse=ECR_Ignore,bTraceType=False,bStaticObject=False)
+DefaultChannelResponses=(Channel=ECC_GameTraceChannel3,Name="FfBlast",DefaultResponse=ECR_Overlap,bTraceType=True,bStaticObject=False)
+DefaultChannelResponses=(Channel=ECC_GameTraceChannel4,Name="FfItem",DefaultResponse=ECR_Overlap,bTraceType=False,bStaticObject=False)
[/Script/Engine.Engine]
bUseFixedFrameRate=False
bSmoothFrameRate=False
[/Script/Engine.RendererSettings]
r.DefaultFeature.AutoExposure=False
r.VSync=0
[/Script/OnlineSubsystemUtils.IpNetDriver]
NetServerMaxTickRate=20
MaxNetTickRate=20
